"""empty message

Revision ID: 16aa768bd553
Revises: f616d9d42f92
Create Date: 2016-10-03 12:09:25.151127

"""

# revision identifiers, used by Alembic.
revision = '16aa768bd553'
down_revision = 'f616d9d42f92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_my_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=20), nullable=False),
    sa.Column('value', sa.BLOB(length=16000000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aws_my_db_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=20), nullable=False),
    sa.Column('value', sa.BLOB(length=16000000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('providers_comparison_aws')
    op.drop_table('amazon_rds_engine_comparison')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aws_my_resources')
    op.drop_table('aws_my_db_resources')
    op.create_table('amazon_rds_engine_comparison',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('id_aws_key', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_aws_key'], [u'aws_key.id'], name=u'amazon_rds_engine_comparison_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('providers_comparison_aws',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('id_aws_key', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_aws_key'], [u'aws_key.id'], name=u'providers_comparison_aws_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
