"""empty message

Revision ID: 2f80dcca0587
Revises: f089fc9a515b
Create Date: 2016-10-31 18:09:46.805721

"""

# revision identifiers, used by Alembic.
revision = '2f80dcca0587'
down_revision = 'f089fc9a515b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('task_name', sa.Unicode(length=128), nullable=False),
    sa.Column('argument_signature', sa.String(length=128), nullable=False),
    sa.Column('error', sa.Unicode(length=1024), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_name', 'argument_signature')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_status')
    ### end Alembic commands ###
