"""empty message

Revision ID: 56c64544a182
Revises: cb917a0f03c9
Create Date: 2017-04-15 01:12:17.714655

"""

# revision identifiers, used by Alembic.
revision = '56c64544a182'
down_revision = 'cb917a0f03c9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('multikey_key', 'billing_bucket_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('multikey_key', 'billing_bucket_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###
