"""empty message

Revision ID: 83bed86e1cba
Revises: 16aa768bd553
Create Date: 2016-10-05 04:06:20.500503

"""

# revision identifiers, used by Alembic.
revision = '83bed86e1cba'
down_revision = '16aa768bd553'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_bucket_metadata_cache',
    sa.Column('bucket', sa.Unicode(63), nullable=False),
    sa.Column('metadata_cache', sa.BLOB(length=16000000), nullable=True),
    sa.PrimaryKeyConstraint('bucket')
    )
    op.create_table('s3_bucket_metadata_summary',
    sa.Column('bucket', sa.Unicode(63), nullable=False),
    sa.Column('metadata_summary', sa.BLOB(length=16000000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bucket')
    )
    op.create_table('aws_key_s3_bucket',
    sa.Column('id_aws_key', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.Unicode(length=63), nullable=False),
    sa.ForeignKeyConstraint(['id_aws_key'], ['aws_key.id'], ),
    sa.PrimaryKeyConstraint('id_aws_key', 'bucket')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3_bucket_metadata_summary')
    op.drop_table('s3_bucket_metadata_cache')
    op.drop_table('aws_key_s3_bucket')
    ### end Alembic commands ###
