"""empty message

Revision ID: 93d33c6f7725
Revises: None
Create Date: 2016-04-21 02:08:06.362118

"""

# revision identifiers, used by Alembic.
revision = '93d33c6f7725'
down_revision = None

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils.types.encrypted


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_pricing',
    sa.Column('offer', sa.String(length=63), nullable=False),
    sa.Column('version', sa.String(length=63), nullable=False),
    sa.Column('etag', sa.String(length=63), nullable=True),
    sa.Column('value', sa.BLOB(length=16000000), nullable=False),
    sa.PrimaryKeyConstraint('offer', 'version')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=32), nullable=True),
    sa.Column('lastname', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aws_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('secret', sqlalchemy_utils.types.encrypted.EncryptedType(), nullable=False),
    sa.Column('pretty', sa.String(length=63), nullable=True),
    sa.Column('billing_bucket_name', sa.String(length=63), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session_token',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session_token')
    op.drop_table('aws_key')
    op.drop_table('user')
    op.drop_table('aws_pricing')
    ### end Alembic commands ###
