"""empty message

Revision ID: cb917a0f03c9
Revises: 7ed30ae8f391
Create Date: 2017-04-12 13:03:23.947021

"""

# revision identifiers, used by Alembic.
revision = 'cb917a0f03c9'
down_revision = '7ed30ae8f391'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aws_key', sa.Column('last_duration', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aws_key', 'last_duration')
    ### end Alembic commands ###
