"""RDS Engin comparison

Revision ID: cbae861a97fc
Revises: 97076c2d60f5
Create Date: 2016-06-14 14:22:19.275965

"""

# revision identifiers, used by Alembic.
revision = 'cbae861a97fc'
down_revision = '97076c2d60f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_rds_engine_comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aws_key', sa.Integer(), nullable=False),
    sa.Column('value', sa.BLOB(length=16000000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_aws_key'], ['aws_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amazon_rds_engine_comparison')
    ### end Alembic commands ###
