"""empty message

Revision ID: dcc6e55ba68c
Revises: 2f80dcca0587
Create Date: 2016-11-01 04:52:43.325664

"""

# revision identifiers, used by Alembic.
revision = 'dcc6e55ba68c'
down_revision = '2f80dcca0587'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3_bucket_metadata_cache')
    op.drop_table('s3_bucket_metadata_summary')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_bucket_metadata_summary',
    sa.Column('bucket', mysql.VARCHAR(length=63), nullable=False),
    sa.Column('metadata_summary', mysql.MEDIUMBLOB(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('bucket'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('s3_bucket_metadata_cache',
    sa.Column('bucket', mysql.VARCHAR(length=63), nullable=False),
    sa.Column('metadata_cache', mysql.MEDIUMBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('bucket'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
