"""empty message

Revision ID: eca04db5c363
Revises: dcc6e55ba68c
Create Date: 2016-12-05 22:59:16.105566

"""

# revision identifiers, used by Alembic.
revision = 'eca04db5c363'
down_revision = 'dcc6e55ba68c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('report_last_emailed_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'report_last_emailed_at')
    ### end Alembic commands ###