"""empty message

Revision ID: f089fc9a515b
Revises: fd8b14d0b130
Create Date: 2016-10-07 13:23:21.625539

"""

# revision identifiers, used by Alembic.
revision = 'f089fc9a515b'
down_revision = 'fd8b14d0b130'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    ### end Alembic commands ###
