"""add account_id

Revision ID: f35ff3668c49
Revises: 01692304455c
Create Date: 2017-07-19 09:40:01.841202

"""

# revision identifiers, used by Alembic.
revision = 'f35ff3668c49'
down_revision = '62f13d586d4e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aws_key', sa.Column('account_id', sa.Unicode(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aws_key', 'account_id')
    ### end Alembic commands ###
