"""empty message

Revision ID: f616d9d42f92
Revises: b0c57024a389
Create Date: 2016-09-16 12:55:04.948526

"""

# revision identifiers, used by Alembic.
revision = 'f616d9d42f92'
down_revision = 'b0c57024a389'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_cost_by_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=20), nullable=False),
    sa.Column('value', sa.BLOB(length=16000000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aws_cost_by_resource')
    ### end Alembic commands ###
